allthings/node-sdk

src/rest/methods/registrationCode.test.ts
src/rest/methods/registrationCode.ts

quick change for the tenants as registration codes branch on nisaba

chore: registraionCodeDelete now returns a bool

---

README.md

To tell people the behaviour of this.

Adding documentation for apiUrl

---

src/constants.ts
src/rest/request.ts

I guess before it was a "linear backoff"..

fix: make "exponential backoff" on 503 retries.. actually exponential

---

src/rest/methods/agent.test.ts
src/rest/oauth.ts
src/rest/request.test.ts
src/rest/request.ts

Adds a few more logging spots to log requests, responses, and oauth calls
Side note to mostly self: `request.ts` could use a refactor at some point.

feat: improved request/response/oauth logging

---

README.md
src/rest/index.ts
src/rest/methods/notification.test.ts
src/rest/methods/notification.ts
src/rest/types.ts
src/utils/stringToDate.ts
test/helpers.ts

feat: add Notifications

---

src/rest/methods/user.ts

If something is wrong there, it's really confusing while using it. 
Is this assumption right?

Fixing incorrect variable name

---

test/docker-compose.yml

Adds new rope container to docker-compose for tests on Buildkite. Should address https://github.com/allthings/node-sdk/pull/114#issuecomment-441442785

chore: add rope to test docker-compose

---

package.json
src/rest/methods/agent.ts
src/rest/methods/user.test.ts
src/rest/methods/user.ts
src/rest/methods/utilisationPeriod.test.ts
test/helpers.ts

This resolves #123
This is a breaking change: To make the password optional, I had to move the param to the end.

make password in createUser optional

---

.buildkite/pipeline.yml
package.json
yarn.lock

chore: APP-2148: switch from nsp to yarn audit

chore: APP-2148: switch from nsp to yarn audit

---

src/rest/methods/user.ts
test/docker-compose.yml

This PR adds a `nativeAppInstallIds` field to the `User` interface.

fix: add nativeAppInstallIds user field

---

src/oauth/clientCredentialsGrant.test.ts
src/oauth/clientCredentialsGrant.ts
src/oauth/index.ts
src/rest/index.test.ts
src/rest/oauthObtainTokenFromClientOptions.test.ts
src/rest/oauthObtainTokenFromClientOptions.ts

This PR implements adding the client credentials grant type, based on the branch adding authorization code grant type by @svlapin

feat: add client credentails grant type

---

README.md
src/rest/index.ts
src/rest/methods/userRelation.test.ts
src/rest/methods/userRelation.ts
src/rest/types.ts

Add the user relations endpoints which are required for nisaba

feat: add the user-relations endpoints

---

src/rest/index.ts
src/rest/methods/userRelation.test.ts
src/rest/methods/userRelation.ts
src/rest/types.ts

I put the Enum in the wrong place -.-

fix: wrong Enum exports

---

src/index.ts

stupid me missed the index.ts file

fix: missed the index.ts for the export of the EnumUserRelationType

---

package.json
src/rest/methods/userRelation.test.ts
src/rest/methods/userRelation.ts
yarn.lock

adjusted the user relation tests to conform with the latest changes to the response format of the api.

fix: adjust the user relation test to the latest response format

---

src/rest/methods/user.ts

This PR adds the new `communicationPreferences` field to the `IUser` interface.
Related API PR: https://github.com/allthings/php-prod/pull/902

feat: add communicationPreferences to IUser

---

src/rest/methods/user.ts

This PR fixes the shape of the `communicationPreferences` property of `IUser`.

fix: user communicationPreferences shape

---

src/index.ts
src/rest/index.ts
src/rest/methods/user.ts

This PR adds `EnumCommunicationPreferenceChannel` to the SDK exports.

feat: export user communication preferences Enum

---

README.md
src/rest/index.ts
src/rest/methods/utilisationPeriod.test.ts
src/rest/methods/utilisationPeriod.ts
src/rest/types.ts

Add new SDK method for `/v1/utilisation-periods/${slug}/registration-codes` API endpoint

feat: add utilisationPeriodAddRegistrationCode

---

src/rest/methods/userRelation.test.ts
src/rest/methods/userRelation.ts

Add optional jobRoles to userRelations

feat: add optional jobroles

---

package.json

fix for:
```
yarn audit v1.15.2
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ high          │ Prototype Pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ handlebars                                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=4.3.0                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ jest                                                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ jest > jest-cli > …
```

chore: fix audit regarding handlebars

---

src/rest/methods/utilisationPeriod.test.ts
src/rest/methods/utilisationPeriod.ts

Add `type` and `endDate` to `utilisationPeriodCreate` method

feat: add type and endDate to utilisation period create

---

package.json
test/docker-compose.yml

This PR implements :arrow_up: :arrow_down:

chore: fix security check

---

package.json

This PR implements fixing security check errors.

chore: fix secuity checks

---

src/rest/methods/group.test.ts
src/rest/methods/group.ts
src/rest/methods/property.test.ts
src/rest/methods/property.ts
src/rest/methods/unit.test.ts
src/rest/methods/unit.ts

see: https://allthings.atlassian.net/browse/APP-3340

feat: propertyOwner + billingPeriod for main entities

---

package.json
yarn.lock

This reverts commit 29d1250daacecabbf502c3555ebbc3102b874e3e.

fix: revert "⬆️ Update dependency semantic-release to v16 (#307)"

---

package.json
yarn.lock

Re
* https://github.com/semantic-release/npm/pull/115
* #317 
* https://buildkite.com/allthings/node-sdk/builds/4586#8e551588-e2eb-49cc-9c0f-40e97626166c
* https://allthings-team.slack.com/archives/C0AA1N0CX/p1580371041037100

fix: pin @semantic-release/npm 5.0.5

---

src/rest/methods/conversation.test.ts
src/rest/methods/conversation.ts
src/rest/types.ts
test/constants.ts

Added optional inputChannel to message payload

feat: added input channel set up for messages

---

src/index.ts

Added interfaces and enums to the root export

fix: add type to root export

---

src/rest/methods/idLookup.test.ts
src/rest/methods/idLookup.ts
src/rest/methods/user.test.ts

lookup just users or explicit usertypes (agents / tenants).
https://allthings.atlassian.net/browse/APP-3599

feat: lookup users or explicitly agents or tenants

---

src/rest/methods/idLookup.test.ts
src/rest/methods/idLookup.ts
src/rest/types.ts

Export possible userTypes for lookUp endpoint.
Forgot that in the previous PR for APP-3520

fix: export userTypes

---

src/rest/methods/app.ts

This PR implements adding `emailToTicketEnabled` to the app interface

chore: update app interface

---

package.json
src/rest/methods/ticket.ts
yarn.lock

This PR adds a token key the ticket interface.
https://allthings.atlassian.net/browse/APP-5320

chore: add token as a parameter

---

.buildkite/pipeline.yml
bin/preversion.sh

@peinwag @svlapin Can this be a solution for: https://allthings-team.slack.com/archives/C0AA1N0CX/p1580379413040900?thread_ts=1580371041.037100&cid=C0AA1N0CX ?

chore: omit prerelease-script on buildkite
